FROM public.ecr.aws/lambda/python:3.8.2024.05.29.10-x86_64

COPY ./requirements.txt ${LAMBDA_TASK_ROOT}

RUN yum update -y
RUN yum install wget gzip gcc g++ gcc-c++ build-essential make automake libtool openjdk-8-jdk -y
RUN pip install --upgrade pip setuptools \
    && pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt



RUN wget https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz \
    && tar -xf mecab-0.996-ko-0.9.2.tar.gz \
    && cd mecab-0.996-ko-0.9.2 \
    && ./configure \
    && make \
    && make check \
    && make install \
    && cd .. \
    && rm -rf mecab-0.996-ko-0.9.2.tar.gz

RUN wget https://bitbucket.org/eunjeon/mecab-ko-dic/downloads/mecab-ko-dic-2.1.1-20180720.tar.gz \
    && tar -xf mecab-ko-dic-2.1.1-20180720.tar.gz \
    && cd mecab-ko-dic-2.1.1-20180720 \
    && ./configure \
    && ./autogen.sh \
    && make \
    && make install \
    && cd .. \
    && rm -rf mecab-ko-dic-2.1.1-20180720.tar.gz

COPY ./main.py ${LAMBDA_TASK_ROOT}
COPY ./routers ${LAMBDA_TASK_ROOT}/routers
COPY ./util ${LAMBDA_TASK_ROOT}/util
COPY .env ${LAMBDA_TASK_ROOT}
COPY ./usedata ${LAMBDA_TASK_ROOT}/usedata


CMD [ "main.handler" ]